### ISSUE TITLE
Is it a good, bad or neutral thing that md files gets installed alongside the generated html?

### ISSUE THREAD

**Issue by eddelbuettel** [djvanderlaan/simplermarkdown#17]
Loving `simplermarkdown` and in the process of converted a likely half-dozen packages.  One thing I noticed, though, is as I converted my vignette files to `vignettes/*.md` (which in and by itself is almost enough to switch) I noticed that they end up in `doc/`.  Example from `drat` which has multiple:

```sh
edd@rob:~/git/drat(master)$ ls -l vignettes/*md
-rw-rw-r-- 1 edd edd 3570 Nov 28 08:28 vignettes/CombiningDratAndTravis.md
-rw-rw-r-- 1 edd edd 7091 Dec  1 07:44 vignettes/DratFAQ.md
-rw-rw-r-- 1 edd edd 6514 Dec  1 07:43 vignettes/DratForPackageAuthors.md
-rw-rw-r-- 1 edd edd 2796 Nov 28 08:28 vignettes/DratForPackageUsers.md
-rw-rw-r-- 1 edd edd 8217 Nov 28 08:28 vignettes/DratStepByStep.md
-rw-rw-r-- 1 edd edd 4005 Nov 28 08:28 vignettes/WhyDrat.md
edd@rob:~/git/drat(master)$ tar tvzf drat_0.2.2.tar.gz | grep doc/
drwxr-xr-x edd/edd           0 2021-12-01 17:41 drat/inst/doc/
-rw-r--r-- edd/edd       12597 2021-12-01 17:41 drat/inst/doc/CombiningDratAndTravis.html
-rw-r--r-- edd/edd        3570 2021-11-28 08:28 drat/inst/doc/CombiningDratAndTravis.md
-rw-r--r-- edd/edd       13605 2021-12-01 17:41 drat/inst/doc/DratFAQ.html
-rw-r--r-- edd/edd        7091 2021-12-01 07:44 drat/inst/doc/DratFAQ.md
-rw-r--r-- edd/edd       13731 2021-12-01 17:41 drat/inst/doc/DratForPackageAuthors.html
-rw-r--r-- edd/edd        6514 2021-12-01 07:43 drat/inst/doc/DratForPackageAuthors.md
-rw-r--r-- edd/edd        9117 2021-12-01 17:41 drat/inst/doc/DratForPackageUsers.html
-rw-r--r-- edd/edd        2796 2021-11-28 08:28 drat/inst/doc/DratForPackageUsers.md
-rw-r--r-- edd/edd       17326 2021-12-01 17:41 drat/inst/doc/DratStepByStep.html
-rw-r--r-- edd/edd        8217 2021-11-28 08:28 drat/inst/doc/DratStepByStep.md
-rw-r--r-- edd/edd       10210 2021-12-01 17:41 drat/inst/doc/WhyDrat.html
-rw-r--r-- edd/edd        4005 2021-11-28 08:28 drat/inst/doc/WhyDrat.md
edd@rob:~/git/drat(master)$ 
```

Do you control that via the `VignetteBuilder` hook for which you supply an entry?  Should we, or should we not, ship the md?  I do not have very strong feelings as these files tend to be tiny, especially compared to some of the _monstrous_ html files generated by some other defaults (when fonts, css, plots, ... may get embedded).

If this is on purpose, never mind and please close this.

**Comment by djvanderlaan** [comment]
It wasn't intentionally and not something I explicitly coded that way. Apparently it is default behaviour of `R CMD build`:

> When R CMD build builds the vignettes, it copies these and the vignette sources from directory vignettes to inst/doc. 

See [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Writing-package-vignettes). So the sources are copied to `inst/doc` by `R CMD build`. I just checked with one of my packages that still uses `knitr`, there the `Rmd` files are also copied to `inst/doc`. 

So it seems that this is intended behaviour from `R CMD build`. So, I guess keeping it this way would make sense.

**Comment by djvanderlaan** [comment]
And good to hear that you are using it, and also nice to see that I didn't already have a bunch of other issues from you.

**Comment by eddelbuettel** [comment]
Guess I lost track of that because I often use prebuilt vignettes too :)

**Comment by eddelbuettel** [comment]
Yes count now at two,  Expect it to climb :)

**Comment by djvanderlaan** [comment]
Not too bad for a new package :)
