### ISSUE TITLE
Error Message Clarification

### ISSUE THREAD

**Issue by brodieG** [djvanderlaan/simplermarkdown#20]
I just started testing `simplermarkdown` and independently ran into #18.  It took me a while to figure out what was going on because I had an old version of Pandoc with decidedly unhelpful error messages.  I didn't actually realize the error was from Pandoc until I debugged `mdweave` and stepped through.  Finally I figured out the problem by upgrading Pandoc, getting a better error message, and figuring out that I had to include a meta in the code for it work.

Point is, it might be helpful to users if the code checks the return value of the `system` calls, and if there are errors there, generates an error indicating the external software causing the error along with the error code.  E.g. in this case it might have been something like:

> Pandoc Error in JSON->MD Step: Parse Error (err code 64)

Or some such.  This would allow the traditional `traceback` etc. tools produce expected outcomes, and the error is a little easier to track down (although with my version of Pandoc the message was so terse I could not have figured out the problem).

I haven't committed yet to using this package in my own, so you should not worry about this unless you find this an improvement you find useful yourself.  If you'd like I could submit a PR to implement.

**Comment by djvanderlaan** [comment]
Thanks. Good suggestion. I will look into it.

This specific error message is fixed, by the way (see issue #18 ). Not on CRAN yet, as I am waiting for CRAN to open again (next week).

**Comment by djvanderlaan** [comment]
I am trying to figure out why you don't get to see the error message (I do). I am using `system` to run `pandoc`. I am probably running into the following feature of `system`: 

>  For GUIs, what happens to output sent to stdout or stderr if intern = FALSE is interface-specific, and it is unsafe to assume that such messages will appear on a GUI console (they do on the macOS GUI's console, but not on some others).

Could you check something for me?  Does running the following command result in a message for you? 

```
suppressWarnings(result <- system2("pandoc", "--foobar"))
```
It should result in something like (at least that is what it does for me):
```
> suppressWarnings(result <- system2("pandoc", "--foobar"))
Unknown option --foobar.
Try pandoc --help for more information.
```

**Comment by brodieG** [comment]
Sorry, I was less clear than I could have been.  I saw:
```
> mdweave('README-src.md', 'README.md')
JSON parse error
> traceback()
No traceback available 
```
The README was a big complicated file, without a meta section.  Adding a:

**Comment by brodieG** [comment]
I think simply using `intern=TRUE` gets you 90% of the way there.

```
> x <- system("pandoc --foo", intern=TRUE)
Unknown option --foo.
Try pandoc --help for more information.
Warning message:
In system("pandoc --foo", intern = TRUE) :
  running command 'pandoc --foo' had status 6
```

This gives a warning, which we can change to error with `options(warn=2)` if needed, and also shows the command that caused the error along with the error code.

**Comment by djvanderlaan** [comment]
The code now generates and error in case of an error with pandoc. Including the command, and the step in the process which the error occurs. Also, the temporary files are kept in case of an error; that should make debugging easier.
