### ISSUE TITLE
eval=FALSE option for code blocks?

### ISSUE THREAD

**Issue by markvanderloo** [djvanderlaan/simplermarkdown#27]
I'm finally starting to use this package. 

I may have not RTFM enough but I think there is no `eval=FALSE`  option. This comes in handy if you want to show e.g. how to install the package, like so:

````
To install the package use
```{.R eval=FALSE}
install.packages("foo")
```
````

(This example may seem superfluous but I've had many an email by users who have been mislead into thinking that `install_github` is the default way to install a package.)

**Comment by djvanderlaan** [comment]
Hi Mark,

Sorry.

Quick solution is to not use the `.R` in the header of the code-block. That is the trigger to evaluate the code. However, this will also mean the code in the block is not syntax highlighted for R. So you are right, better to add an `eval=FALSE` option (or something similar).
